version: 0.2
        
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - echo Preparing for build...
  build:
    on-failure: ABORT
    commands:
      - echo Building Next.js app…
      - npm run build
      - echo Building Docker image…
      - docker build -t portfolio .
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed successfully!
