version: 0.2

env:
  parameter-store:
    SPOTIFY_CLIENT_ID: "/prod/portfolio/spotify/SPOTIFY_CLIENT_ID"
    SPOTIFY_CLIENT_SECRET: "/prod/portfolio/spotify/SPOTIFY_CLIENT_SECRET"
    SPOTIFY_REFRESH_TOKEN: "/prod/portfolio/spotify/SPOTIFY_REFRESH_TOKEN"
phases:
  install:
    on-failure: ABORT
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    on-failure: ABORT
    commands:
      - echo Preparing for build...
  build:
    on-failure: ABORT
    commands:
      - echo Building Next.js app…
      - npm run build
      - echo Building Docker image…
      - docker build . -t portfolio --build-arg SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID} --build-arg SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET} --build-arg SPOTIFY_REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN}
  post_build:
    on-failure: ABORT
    commands:
      - echo Build completed successfully!
